### ISSUE TITLE
Agar.io update seems to have broken this script

### ISSUE THREAD

**Issue by vanlellan** [ibash/agar#4]
$npm start

> agar-sandbox@1.0.0 start /home/evan/agar
> node server.js

Canvas not installed. Cannot export png.
Proxy server started on port: 8888
Got websocket connection, initializing game.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND undefined
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "node" "/home/evan/.linuxbrew/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! agar-sandbox@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the agar-sandbox@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the agar-sandbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls agar-sandbox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/evan/agar/npm-debug.log

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/home/evan/.linuxbrew/bin/npm', 'start' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /home/evan/.linuxbrew/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart agar-sandbox@1.0.0
7 info start agar-sandbox@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info agar-sandbox@1.0.0 Failed to exec start script
10 verbose stack Error: agar-sandbox@1.0.0 start: `node server.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/home/evan/.linuxbrew/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/home/evan/.linuxbrew/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid agar-sandbox@1.0.0
12 verbose cwd /home/evan/agar
13 error Linux 3.13.0-55-generic
14 error argv "node" "/home/evan/.linuxbrew/bin/npm" "start"
15 error node v0.12.4
16 error npm  v2.10.1
17 error code ELIFECYCLE
18 error agar-sandbox@1.0.0 start: `node server.js`
18 error Exit status 1
19 error Failed at the agar-sandbox@1.0.0 start script 'node server.js'.
19 error This is most likely a problem with the agar-sandbox package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node server.js
19 error You can get their info via:
19 error     npm owner ls agar-sandbox
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by amitrahav** [comment]
same here

**Comment by ibash** [comment]
Hi,

Taking a looking at this issue on my phone, any thoughts as to what it is?
